/**
 * Kosakata resmi provinsi & kota Indonesia → Jepang (katakana/kanji)
 * untuk Surat Tanggungan versi Jepang dan preview KK JP.
 */

/** 38 Provinsi */
export const PROVINCE_JP: Record<string, string> = {
  ACEH: 'アチェ',
  'SUMATRA UTARA': '北スマトラ',
  'SUMATERA UTARA': '北スマトラ',
  'SUMATRA BARAT': '西スマトラ',
  'SUMATERA BARAT': '西スマトラ',
  RIAU: 'リアウ',
  'KEPULAUAN RIAU': 'リアウ諸島',
  JAMBI: 'ジャンビ',
  'SUMATRA SELATAN': '南スマトラ',
  'SUMATERA SELATAN': '南スマトラ',
  BENGKULU: 'ベンクル',
  'KEPULAUAN BANGKA BELITUNG': 'バンカ・ブリトゥン諸島',
  'BANGKA BELITUNG': 'バンカ・ブリトゥン諸島',
  LAMPUNG: 'ランプン',
  BANTEN: 'バンテン',
  'DKI JAKARTA': 'ジャカルタ首都特別州',
  'JAWA BARAT': '西ジャワ',
  'JAWA TENGAH': '中部ジャワ',
  'DI YOGYAKARTA': 'ジョグジャカルタ特別州',
  'DAERAH ISTIMEWA YOGYAKARTA': 'ジョグジャカルタ特別州',
  'JAWA TIMUR': '東ジャワ',
  BALI: 'バリ',
  'NUSA TENGGARA BARAT': '西ヌサ・トゥンガラ',
  NTB: '西ヌサ・トゥンガラ',
  'NUSA TENGGARA TIMUR': '東ヌサ・トゥンガラ',
  NTT: '東ヌサ・トゥンガラ',
  'KALIMANTAN BARAT': '西カリマンタン',
  'KALIMANTAN TENGAH': '中部カリマンタン',
  'KALIMANTAN SELATAN': '南カリマンタン',
  'KALIMANTAN TIMUR': '東カリマンタン',
  'KALIMANTAN UTARA': '北カリマンタン',
  'SULAWESI UTARA': '北スラウェシ',
  GORONTALO: 'ゴロンタロ',
  'SULAWESI TENGAH': '中部スラウェシ',
  'SULAWESI BARAT': '西スラウェシ',
  'SULAWESI SELATAN': '南スラウェシ',
  'SULAWESI TENGGARA': '南東スラウェシ',
  MALUKU: 'マルク',
  'MALUKU UTARA': '北マルク',
  PAPUA: 'パプア',
  'PAPUA BARAT': '西パプア',
  'PAPUA PEGUNUNGAN': '山岳パプア',
  'PAPUA TENGAH': '中部パプア',
  'PAPUA SELATAN': '南パプア',
  'PAPUA BARAT DAYA': '南西パプア',
};

/** 98 Kota */
export const CITY_JP: Record<string, string> = {
  // Sumatra
  'BANDA ACEH': 'バンダ・アチェ',
  LANGSA: 'ラングサ',
  LHOKSEUMAWE: 'ロクスマウェ',
  SABANG: 'サバン',
  SUBULUSSALAM: 'スブルッサラム',
  BINJAI: 'ビンジャイ',
  GUNUNGSITOLI: 'グヌンシトリ',
  MEDAN: 'メダン',
  'PADANG SIDEMPUAN': 'パダン・シデンプアン',
  PEMATANGSIANTAR: 'プマタンシアンタール',
  SIBOLGA: 'シボルガ',
  TANJUNGBALAI: 'タンジュンバライ',
  'TANJUNG BALAI': 'タンジュンバライ',
  'TEBING TINGGI': 'トゥビン・ティンギ',
  BUKITTINGGI: 'ブキッティンギ',
  PADANG: 'パダン',
  'PADANG PANJANG': 'パダン・パンジャン',
  PARIAMAN: 'パリアマン',
  PAYAKUMBUH: 'パヤクンブ',
  SAWAHLUNTO: 'サワルント',
  SOLOK: 'ソロク',
  JAMBI: 'ジャンビ',
  'SUNGAI PENUH': 'スンガイプヌ',
  SUNGAIPENUH: 'スンガイプヌ',
  DUMAI: 'ドゥマイ',
  PEKANBARU: 'プカンバル',
  BATAM: 'バタム',
  TANJUNGPINANG: 'タンジュンピナン',
  'TANJUNG PINANG': 'タンジュンピナン',
  BENGKULU: 'ベンクル',
  LUBUKLINGGAU: 'ルブクリンガウ',
  'PAGAR ALAM': 'パガル・アラム',
  PALEMBANG: 'パレンバン',
  PRABUMULIH: 'プラブムリ',
  PANGKALPINANG: 'パンカルピナン',
  'PANGKAL PINANG': 'パンカルピナン',
  'BANDAR LAMPUNG': 'バンダールランプン',
  METRO: 'メトロ',
  // Jawa
  CILEGON: 'チレゴン',
  SERANG: 'セラン',
  TANGERANG: 'タンゲラン',
  'TANGERANG SELATAN': '南タンゲラン',
  'JAKARTA BARAT': '西ジャカルタ',
  'JAKARTA PUSAT': '中央ジャカルタ',
  'JAKARTA SELATAN': '南ジャカルタ',
  'JAKARTA TIMUR': '東ジャカルタ',
  'JAKARTA UTARA': '北ジャカルタ',
  BANDUNG: 'バンドン',
  BANJAR: 'バンジャル',
  BEKASI: 'ブカシ',
  BOGOR: 'ボゴール',
  CIMAHI: 'チマヒ',
  CIREBON: 'チルボン',
  DEPOK: 'デポック',
  SUKABUMI: 'スカブミ',
  TASIKMALAYA: 'タシクマラヤ',
  MAGELANG: 'マゲラン',
  PEKALONGAN: 'プカロンガン',
  SALATIGA: 'サラティガ',
  SEMARANG: 'スマラン',
  SURAKARTA: 'スラカルタ',
  SOLO: 'スラカルタ',
  TEGAL: 'トゥガル',
  YOGYAKARTA: 'ジョグジャカルタ',
  BATU: 'バトゥ',
  BLITAR: 'ブリタル',
  KEDIRI: 'クディリ',
  MADIUN: 'マディウン',
  MALANG: 'マラン',
  MOJOKERTO: 'モジョケルト',
  PASURUAN: 'パスルアン',
  PROBOLINGGO: 'プロボリンゴ',
  SURABAYA: 'スラバヤ',
  // Bali & Nusa Tenggara
  DENPASAR: 'デンパサール',
  BIMA: 'ビマ',
  MATARAM: 'マタラム',
  KUPANG: 'クパン',
  // Kalimantan
  PONTIANAK: 'ポンティアナック',
  SINGKAWANG: 'シンカワン',
  BANJARBARU: 'バンジャルバル',
  BANJARMASIN: 'バンジャルマシン',
  'PALANGKA RAYA': 'パランカラヤ',
  BALIKPAPAN: 'バリクパパン',
  BONTANG: 'ボンタン',
  SAMARINDA: 'サマリンダ',
  TARAKAN: 'タラカン',
  // Sulawesi
  GORONTALO: 'ゴロンタロ',
  MAKASSAR: 'マカッサル',
  PALOPO: 'パロポ',
  PAREPARE: 'パレパレ',
  BAUBAU: 'バウバウ',
  KENDARI: 'クンダリ',
  PALU: 'パル',
  BITUNG: 'ビトゥン',
  KOTAMOBAGU: 'コタモバグ',
  MANADO: 'マナド',
  TOMOHON: 'トモホン',
  // Maluku & Papua
  AMBON: 'アンボン',
  TUAL: 'トゥアル',
  TERNATE: 'テルナテ',
  'TIDORE KEPULAUAN': 'ティドレ諸島',
  JAYAPURA: 'ジャヤプラ',
  SORONG: 'ソロン',
};
